#tomcat
#server.ssl.key-store :  .keystore
#server.ssl.key-store-password :  jiawei1207
#server.ssl.keyStoreType :  JKS
#server.ssl.keyAlias: tomcat
server:
  port: 8084
  session-timeout: 2000
  tomcat:
    uri-encoding: UTF-8
    compression: off
    
mysql:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/mall_db?useUnicode=true&characterEncoding=utf-8&useSSL=true
  username: root
  password: 123456

dataSource:
  initialPoolSize: 1
  minPoolSize: 1
  maxActive: 10
  maxWait: 10000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  testWhileIdle: true
  testOnBorrow: true
  testOnReturn: false
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20